benchmarks:
- sqlite3_ossfuzz
concurrent_builds: null
description: null
docker_registry: gcr.io/fuzzbench
experiment: instrument
experiment_filestore: /home/eric/experiment-data
fuzzers:
- aflplusplus
git_hash: d4e201c6fbf9bffc14a2a85537cf4374c8bb3a56
local_experiment: true
max_total_time: 86400
no_dictionaries: false
no_seeds: false
oss_fuzz_corpus: false
report_filestore: /home/eric/report-data
runner_machine_type: n1-standard-1
runner_memory: 12GB
runner_num_cpu_cores: 1
trials: 1
